### ISSUE TITLE
[Architecture] Removing custom repositories of public stellarwp packages

### ISSUE THREAD

**Issue by szepeviktor** [stellarwp/schema#22]
I see 2 StellarWP packages with [custom configuration](https://github.com/stellarwp/schema/blob/7300aca7d0691c585c4eb3f4ad4bbad76719e380/composer.json#L49-L62) in `composer.json`.
Composer allows source (git) and dist (zip) downloads.

@borkweb What is up here?

**Comment by borkweb** [comment]
Yeah, that was a holdover from before those were on packagist. Those can be removed. I'll do so!
